FROM node

RUN npm install
RUN npm install -g browserify

RUN npm install --save jquery
RUN npm install --save jquery-browserify

RUN npm install --save markdown-it
RUN npm install --save markdown-it-checkbox
RUN npm install --save markdown-it-footnote
RUN npm install --save markdown-it-imsize
RUN npm install --save markdown-it-highlightjs
RUN npm install --save markdown-it-math
RUN npm install --save markdown-it-mermaid
RUN npm install --save markdown-it-video

RUN npm install --save highlight
RUN npm install --save mathjax
RUN npm install --save ascii2mathml
RUN npm install --save babelify
